export const entries = [
    [
        "北京市",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/11.html"
    ],
    [
        "天津市",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/12.html"
    ],
    [
        "河北省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/13.html"
    ],
    [
        "山西省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/14.html"
    ],
    [
        "内蒙古自治区",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/15.html"
    ],
    [
        "辽宁省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/21.html"
    ],
    [
        "吉林省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/22.html"
    ],
    [
        "黑龙江省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/23.html"
    ],
    [
        "上海市",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/31.html"
    ],
    [
        "江苏省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/32.html"
    ],
    [
        "浙江省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/33.html"
    ],
    [
        "安徽省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/34.html"
    ],
    [
        "福建省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/35.html"
    ],
    [
        "江西省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/36.html"
    ],
    [
        "山东省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/37.html"
    ],
    [
        "河南省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/41.html"
    ],
    [
        "湖北省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/42.html"
    ],
    [
        "湖南省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/43.html"
    ],
    [
        "广东省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/44.html"
    ],
    [
        "广西壮族自治区",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/45.html"
    ],
    [
        "海南省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/46.html"
    ],
    [
        "重庆市",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/50.html"
    ],
    [
        "四川省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/51.html"
    ],
    [
        "贵州省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/52.html"
    ],
    [
        "云南省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/53.html"
    ],
    [
        "西藏自治区",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/54.html"
    ],
    [
        "陕西省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/61.html"
    ],
    [
        "甘肃省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/62.html"
    ],
    [
        "青海省",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/63.html"
    ],
    [
        "宁夏回族自治区",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/64.html"
    ],
    [
        "新疆维吾尔自治区",
        "http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/65.html"
    ]
]